<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"> <!-- name="properties" -->

<xacro:arg name="camera_left" default="true"/>
<xacro:arg name="camera_right" default="true"/>
<xacro:arg name="velodyne_points" default="true"/>
<xacro:arg name="front_laser_points" default="true"/>

<xacro:property name="PI" value="3.1415926835897931"/>
<!--  <xacro:property name="base_height" value="0"/> -->
<<<<<<< HEAD

<xacro:property name="wheelbase" value="2.6"/>
<xacro:property name="track_width" value="1.501"/>

<!-- TODO: fix the car_height -->
<xacro:property name="car_height" value="1.4478"/> <!--1.594"/-->
<xacro:property name="car_width" value="1.765"/>
<xacro:property name="car_length" value="4.166"/>

<!-- TODO: fix the base_mass with its inertia -->
<xacro:property name="base_height" value="1.04"/>
<xacro:property name="base_mass" value="2050"/> <!--1625"/-->
<xacro:property name="base_mass_ixx" value="63"/>
<xacro:property name="base_mass_iyy" value="1048"/>
<xacro:property name="base_mass_izz" value="1111"/>
<xacro:property name="base_mass_ixz" value="-31"/>

<xacro:property name="tire_x" value="${wheelbase/2}"/>
<xacro:property name="tire_y" value="${track_width/2}"/>
<xacro:property name="tire_length" value="0.215"/>
<xacro:property name="tire_diameter" value="0.6468"/>
<xacro:property name="tire_radius" value="0.356"/>

<!-- TODO: fix the tire mass with its inertia -->
<xacro:property name="tire_mass" value="40"/>
<xacro:property name="tire_mass_ixx" value="54"/>
<xacro:property name="tire_mass_iyy" value="56"/>
<xacro:property name="tire_mass_izz" value="104"/>

<xacro:property name="tire_origin">
    <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
</xacro:property>
<xacro:property name="tire_origin_2">
    <origin xyz="-0.3065 -0.765 1.372" rpy="0 0 ${-PI/2}"/>
</xacro:property>
<xacro:property name="tire_origin_3">
    <origin xyz="0.3065 0.765 1.372" rpy="0 0 ${PI/2}"/>
</xacro:property>

<xacro:property name="wheel_geometry">
    <geometry>
        <mesh filename="package://mirvehicle_description/meshes/$(arg robot_name)/wheel.dae" scale="0.0383 0.0383 0.0383"/>
    </geometry>  
</xacro:property>

<xacro:property name="dist_to_bumper" value="2.1"/>
=======
<xacro:property name="base_height" value="1.1159"/>
<xacro:property name="base_mass" value="1562"/>
<xacro:property name="base_mass_ixx" value="566"/>
<xacro:property name="base_mass_iyy" value="1880"/>
<xacro:property name="base_mass_izz" value="2045"/>
<xacro:property name="base_mass_ixz" value="48"/>
<xacro:property name="tyre_x" value="1.30"/>
<xacro:property name="tyre_y" value="0.765"/>
<xacro:property name="tyre_length" value="0.215"/>
<xacro:property name="tyre_r" value="0.66"/>
<xacro:property name="tyre_radius" value="0.3235"/>
<xacro:property name="tyre_mass" value="10"/>
<xacro:property name="tyre_mass_ixx" value="0.305583"/>
<xacro:property name="tyre_mass_iyy" value="0.305583"/>
<xacro:property name="tyre_mass_izz" value="0.5445"/>
<xacro:property name="car_height" value="1.6"/>
<xacro:property name="car_to_bumper" value="2.085"/>
>>>>>>> 392b662d9e2527d674f22fc6910ae1a39eb32f01
<xacro:property name="front_bumper_height" value="${car_height/2}"/>

<xacro:property name="sensor_box" value="0.25"/>
<xacro:property name="camera_box" value="0.1"/>
<<<<<<< HEAD
<xacro:property name="steer_length" value="0.01"/>
<xacro:property name="steer_radius" value="0.1"/>
<xacro:property name="steer_angle_limit" value="0.6"/>

=======
<xacro:property name="tyre_height" value="-0.696"/>
<xacro:property name="str_length" value="0.01"/>
<xacro:property name="str_radius" value="0.1"/>
<xacro:property name="str_angle" value="0.6"/>
<xacro:property name="car_width" value="1.3"/>
>>>>>>> 392b662d9e2527d674f22fc6910ae1a39eb32f01
<xacro:property name="front_laser_points" value="$(arg front_laser_points)"/>
<xacro:property name="velodyne_points" value="$(arg velodyne_points)"/>
<xacro:property name="camera_right" value="$(arg camera_right)"/>
<xacro:property name="camera_left" value="$(arg camera_left)"/>
<<<<<<< HEAD
=======
<xacro:property name="tyre_origin">
    <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
</xacro:property>

>>>>>>> 392b662d9e2527d674f22fc6910ae1a39eb32f01

</robot>
