<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"> <!-- name="properties" -->

<xacro:arg name="camera_left" default="true"/>
<xacro:arg name="camera_right" default="true"/>
<xacro:arg name="velodyne_points" default="true"/>
<xacro:arg name="front_laser_points" default="true"/>

<xacro:property name="PI" value="3.1415926835897931"/>
<!--  <xacro:property name="base_height" value="0"/> -->

<xacro:property name="wheelbase" value="2.6"/>
<xacro:property name="track_width" value="1.501"/>

<xacro:property name="car_height" value="1.594"/>
<xacro:property name="car_width" value="1.765"/>
<xacro:property name="car_length" value="4.166"/>

<xacro:property name="base_height" value="1.0639"/>
<xacro:property name="base_mass" value="1625"/>
<xacro:property name="base_mass_ixx" value="63"/>
<xacro:property name="base_mass_iyy" value="1048"/>
<xacro:property name="base_mass_izz" value="1111"/>
<xacro:property name="base_mass_ixz" value="-31"/>

<xacro:property name="tire_x" value="${wheelbase/2}"/>
<xacro:property name="tire_y" value="${track_width/2}"/>
<xacro:property name="tire_length" value="0.215"/>
<xacro:property name="tire_diameter" value="0.6468"/>
<xacro:property name="tire_radius" value="${tire_diameter/2}"/>
<xacro:property name="tire_mass" value="40"/>
<xacro:property name="tire_mass_ixx" value="54"/>
<xacro:property name="tire_mass_iyy" value="56"/>
<xacro:property name="tire_mass_izz" value="104"/>

<xacro:property name="tire_origin">
    <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
</xacro:property>
<xacro:property name="tire_origin_2">
    <origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
</xacro:property>
<xacro:property name="tire_origin_3">
    <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
</xacro:property>

<xacro:property name="dist_to_bumper" value="2.1"/>
<xacro:property name="front_bumper_height" value="${car_height/2}"/>

<xacro:property name="sensor_box" value="0.25"/>
<xacro:property name="camera_box" value="0.1"/>
<xacro:property name="steer_length" value="0.01"/>
<xacro:property name="steer_radius" value="0.1"/>
<xacro:property name="steer_angle_limit" value="0.6"/>

<xacro:property name="front_laser_points" value="$(arg front_laser_points)"/>
<xacro:property name="velodyne_points" value="$(arg velodyne_points)"/>
<xacro:property name="camera_right" value="$(arg camera_right)"/>
<xacro:property name="camera_left" value="$(arg camera_left)"/>

</robot>
